name: pre-commit in CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Create virtualenv, setup pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
    - name: Run pre-commit in CI
      run: |
        pre-commit run --files $(git ls-files '*.py')
